// app/pages/subscriber/stripe-success.vue
<script setup lang="ts">
const { t } = useI18n()
const route = useRoute()

const code = computed(() => String(route.query.code ?? ''))

const { data: training } = await useFetch('/api/trainings/by-code', {
  query: { code },
})
</script>

<template>
  <main class="container mx-auto py-10 flex justify-center">
    <UCard class="max-w-md w-full text-center">
      <template #header>
        <h2 class="text-2xl font-semibold">{{ t('stripeSuccess.title') }}</h2>
      </template>

      <div class="space-y-4">
        <template v-if="training">
          <p class="text-muted-foreground">{{ t('stripeSuccess.accessNow') }}</p>
          <p class="text-xl font-semibold">{{ training.title }}</p>
          <NuxtLink :to="training.privatePageUrl ?? '#'">
            <UButton class="w-full">{{ t('stripeSuccess.goToTraining') }}</UButton>
          </NuxtLink>
        </template>
        <template v-else>
          <p class="text-muted-foreground">{{ t('stripeSuccess.registered') }}</p>
        </template>

        <NuxtLink to="/subscriber/myspace">
          <UButton variant="outline" class="w-full">{{ t('stripeSuccess.mySpace') }}</UButton>
        </NuxtLink>
      </div>
    </UCard>
  </main>
</template>

// app/subscriber/stripe-success/page.tsx
import { getLang } from "@/lib/getLang";
import { t } from "@/lib/i18n";
import { getByCode } from "@/services/TrainingService";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";

interface Props {
  searchParams: Promise<{ code?: string }>;
}

export default async function StripeSuccessPage({ searchParams }: Props) {
  const lang = await getLang();
  const { code } = await searchParams;
  const training = code ? await getByCode(code) : null;

  return (
    <main className="container mx-auto py-10 flex justify-center">
      <Card className="max-w-md w-full text-center">
        <CardHeader>
          <CardTitle className="text-2xl">{t("stripeSuccess.title", lang)}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {training ? (
            <>
              <p className="text-muted-foreground">{t("stripeSuccess.accessNow", lang)}</p>
              <p className="text-xl font-semibold">{training.title}</p>
              <Link href={training.privatePageUrl ?? "#"} className={buttonVariants({ className: "w-full" })}>
                {t("stripeSuccess.goToTraining", lang)}
              </Link>
            </>
          ) : (
            <p className="text-muted-foreground">{t("stripeSuccess.registered", lang)}</p>
          )}
          <Link href="/subscriber/myspace" className={buttonVariants({ variant: "outline", className: "w-full" })}>
            {t("stripeSuccess.mySpace", lang)}
          </Link>
        </CardContent>
      </Card>
    </main>
  );
}
