// app/trainings/private/portfolio/page.tsx
export default function PortfolioPrivatePage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-10">
      <h1 className="text-3xl font-bold mb-4">Formation Portfolio</h1>
      <p className="text-muted-foreground">Bienvenue dans la formation Portfolio — contenu à venir.</p>
    </main>
  );
}

// app/pages/trainings/private/portfolio.vue
<script setup lang="ts">
const { t } = useI18n()
</script>

<template>
  <main class="max-w-3xl mx-auto px-6 py-10">
    <h1 class="text-3xl font-bold mb-4">Formation Portfolio</h1>
    <p class="text-muted-foreground mb-2">{{ t('formation.comingSoon') }}</p>
    <p class="text-sm text-muted-foreground">{{ t('formation.comingSoonDesc') }}</p>
  </main>
</template>
