// app/components/forum/SubjectCard.vue
<script setup lang="ts">
const { t } = useI18n()

export interface SubjectData {
  id: number
  userId: number
  displayName: string
  type: string
  title: string
  content: string
  status: string
  isPinned: boolean
  isStaff: boolean
  expiresAt: string | null
  createdAt: string
  updatedAt: string | null
  _count: { comments: number }
}

export interface CommentData {
  id: number
  forumSubjectId: number
  forumCommentId: number | null
  userId: number
  displayName: string
  addressedTo: string | null
  destUserId: number | null
  content: string
  status: string
  isPinned: boolean
  isStaff: boolean
  likes: number[]
  createdAt: string
  updatedAt: string | null
}

const props = withDefaults(defineProps<{
  subject: SubjectData
  userId: number
  userRole: string
  displayName: string
  isMod: boolean
  lang: string
  initialExpanded?: boolean
  highlightCommentId?: number
  readOnly?: boolean
  onRefreshList?: () => void
}>(), {
  initialExpanded: false,
  readOnly: false,
})

const expanded = ref(props.initialExpanded)
const comments = ref<CommentData[] | null>(null)
const loading = ref(false)
const replyTo = ref<CommentData | null>(null)
const commentText = ref('')
const submitting = ref(false)
const error = ref('')

const isSubjectOwner = computed(() => props.subject.userId === props.userId)
const withinEditWindowSubject = ref(false)
onMounted(() => {
  withinEditWindowSubject.value = Date.now() - new Date(props.subject.createdAt).getTime() < 3_600_000
})
const canEditSubject = computed(() => !props.readOnly && isSubjectOwner.value && withinEditWindowSubject.value)
const canDeleteSubject = computed(() => !props.readOnly && (isSubjectOwner.value || props.isMod) && props.subject.status === 'open')
const isHiddenSubject = computed(() => props.subject.status === 'hidden')

const subjectContentExpanded = ref(false)
const isSubjectLong = computed(() => props.subject.content.length > 200 || props.subject.content.split('\n').length > 3)
const isEditingSubject = ref(false)
const editTitle = ref(props.subject.title)
const editContent = ref(props.subject.content)
const savingSubject = ref(false)
const confirmDeleteSubject = ref(false)

const picto = computed(() => forumTypePicto(props.subject.type))
const isArchived = computed(() => props.subject.status === 'archived')
const canReactivate = ref(false)
onMounted(() => {
  if (isArchived.value && props.subject.updatedAt) {
    const oneMonthAgo = new Date()
    oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1)
    canReactivate.value = new Date(props.subject.updatedAt) > oneMonthAgo
  }
})

const level0 = computed(() => (comments.value ?? []).filter(c => c.forumCommentId === null))
const pinned = computed(() => level0.value.filter(c => c.isPinned))
const regular = computed(() => level0.value.filter(c => !c.isPinned))

function getReplies(id: number) {
  return (comments.value ?? []).filter(c => c.forumCommentId === id)
}

async function loadComments() {
  loading.value = true
  const data = await $fetch<CommentData[]>(`/api/forum/subjects/${props.subject.id}/comments`)
  comments.value = Array.isArray(data) ? data : []
  loading.value = false
}

onMounted(() => {
  if (props.initialExpanded) loadComments()
})

watch(comments, async () => {
  if (!props.highlightCommentId) return
  await nextTick()
  document.getElementById(`comment-${props.highlightCommentId}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' })
})

async function handleExpand() {
  expanded.value = !expanded.value
  if (expanded.value && comments.value === null) await loadComments()
}

async function handleSaveSubject() {
  if (!editTitle.value.trim() || !editContent.value.trim()) return
  savingSubject.value = true
  await $fetch(`/api/forum/subjects/${props.subject.id}`, {
    method: 'PATCH',
    body: { action: 'update', title: editTitle.value.trim(), content: editContent.value.trim() },
  })
  savingSubject.value = false
  isEditingSubject.value = false
  props.onRefreshList?.()
}

async function handleDeleteSubject() {
  await $fetch(`/api/forum/subjects/${props.subject.id}`, { method: 'DELETE' })
  props.onRefreshList?.()
}

async function handleUnarchiveSubject() {
  await $fetch(`/api/forum/subjects/${props.subject.id}`, {
    method: 'PATCH',
    body: { action: 'open' },
  })
  props.onRefreshList?.()
}

async function handleToggleHideSubject() {
  await $fetch(`/api/forum/subjects/${props.subject.id}`, {
    method: 'PATCH',
    body: { action: isHiddenSubject.value ? 'unhide' : 'hide' },
  })
  props.onRefreshList?.()
}

function handleReply(comment: CommentData) {
  replyTo.value = comment
}

async function handleLike(commentId: number) {
  await $fetch(`/api/forum/comments/${commentId}/like`, { method: 'POST' })
  await loadComments()
}

async function handleSubmitComment() {
  if (!commentText.value.trim()) return
  submitting.value = true
  error.value = ''
  try {
    await $fetch(`/api/forum/subjects/${props.subject.id}/comments`, {
      method: 'POST',
      body: { content: commentText.value.trim(), forumCommentId: replyTo.value?.id ?? null },
    })
    commentText.value = ''
    replyTo.value = null
    await loadComments()
  } catch (e: any) {
    error.value = t(e.data?.error ?? 'ERR_SYSTEM')
  } finally {
    submitting.value = false
  }
}

const cardClass = computed(() => {
  if (props.subject.status === 'hidden') return 'border-red-200 opacity-75'
  if (props.subject.isStaff) return 'border-l-4 border-l-teal-400 bg-zinc-50 dark:bg-zinc-800/40'
  return ''
})
</script>

<template>
  <UCard :class="cardClass">
    <template #header>
      <div class="cursor-pointer select-none" @click="handleExpand">
        <div class="flex items-start gap-3">
          <span class="text-xl mt-0.5">{{ picto }}</span>
          <div class="flex-1 min-w-0">
            <p class="font-semibold leading-tight">{{ subject.title }}</p>
            <div class="flex flex-wrap items-center gap-2 mt-1">
              <UBadge v-if="subject.isPinned" variant="subtle">📌 {{ t('forum.pinned') }}</UBadge>
              <UBadge v-if="subject.status === 'hidden' && isMod" color="error" variant="subtle">🚫 {{ t('forum.hidden') }}</UBadge>
              <span class="text-xs text-muted-foreground">
                <span class="font-medium text-foreground">{{ subject.displayName }}</span>
                · {{ forumFormatDate(subject.createdAt, lang) }}
                <template v-if="subject.updatedAt"> · <em>{{ t('forum.modifiedOn') }} {{ forumFormatDate(subject.updatedAt, lang) }}</em></template>
                <template v-if="subject.expiresAt">
                  · <span :class="new Date(subject.expiresAt) < new Date() ? 'text-destructive' : ''">{{ t('forum.expiresOn') }} {{ forumFormatDate(subject.expiresAt, lang) }}</span>
                </template>
                · {{ subject._count.comments }} {{ t(subject._count.comments === 1 ? 'forum.comment' : 'forum.comments') }}
              </span>
              <div class="flex gap-2 items-center" @click.stop>
                <button v-if="canEditSubject && !isEditingSubject" class="text-xs text-muted-foreground hover:text-foreground transition-colors" @click="isEditingSubject = true; expanded = true">✏️</button>
                <template v-if="canDeleteSubject">
                  <template v-if="confirmDeleteSubject">
                    <button class="text-red-500 hover:text-red-600 transition-colors text-xs" @click="confirmDeleteSubject = false">✖</button>
                    <button class="text-green-500 hover:text-green-600 transition-colors text-xs" @click="handleDeleteSubject">✔</button>
                  </template>
                  <button v-else class="text-xs text-muted-foreground hover:text-destructive transition-colors" @click="confirmDeleteSubject = true">🗑️</button>
                </template>
                <button
                  v-if="(isMod || isSubjectOwner) && canReactivate"
                  class="text-xs text-muted-foreground hover:text-foreground transition-colors"
                  :title="t('forum.unarchive')"
                  @click="handleUnarchiveSubject"
                >📂</button>
                <button
                  v-if="isMod && subject.status !== 'archived'"
                  class="text-xs text-muted-foreground hover:text-foreground transition-colors"
                  @click="handleToggleHideSubject"
                >{{ isHiddenSubject ? '✅' : '🚫' }}</button>
              </div>
            </div>
          </div>
          <UIcon
            name="i-lucide-chevron-down"
            class="w-4 h-4 mt-1 shrink-0 text-muted-foreground transition-transform"
            :class="expanded ? 'rotate-180' : ''"
          />
        </div>
      </div>
    </template>

    <template v-if="expanded">
      <!-- Edition sujet -->
      <div v-if="isEditingSubject" class="space-y-2 pb-2">
        <UInput v-model="editTitle" class="text-sm font-semibold" :maxlength="255" />
        <UTextarea v-model="editContent" :rows="5" class="text-sm" />
        <div class="flex gap-2">
          <UButton size="xs" :disabled="savingSubject || !editTitle.trim() || !editContent.trim()" @click="handleSaveSubject">
            {{ savingSubject ? '…' : t('forum.save') }}
          </UButton>
          <UButton size="xs" variant="ghost" @click="isEditingSubject = false; editTitle = subject.title; editContent = subject.content">
            {{ t('forum.cancel') }}
          </UButton>
        </div>
      </div>

      <!-- Contenu sujet -->
      <template v-else>
        <p
          class="text-sm"
          :class="!subjectContentExpanded && isSubjectLong ? 'overflow-hidden max-h-[3.75rem]' : ''"
          v-html="forumRenderWithLinks(subject.content)"
        />
        <button v-if="isSubjectLong" class="text-yellow-400 hover:text-yellow-500 transition-colors leading-none" @click="subjectContentExpanded = !subjectContentExpanded">
          {{ subjectContentExpanded ? '▲' : '▼' }}
        </button>
      </template>

      <hr class="my-2 border-border/30" />

      <p v-if="loading" class="text-sm text-muted-foreground">{{ t('common.loading') }}</p>
      <p v-else-if="comments !== null && comments.length === 0" class="text-sm text-muted-foreground">{{ t('forum.noComments') }}</p>

      <!-- Commentaires épinglés -->
      <template v-for="comment in pinned" :key="comment.id">
        <div
          :id="`comment-${comment.id}`"
          :class="comment.id === highlightCommentId
            ? 'border-l-4 border-green-500 bg-green-50 dark:bg-green-900/30 rounded-r-md pl-3 py-1'
            : 'border-l-4 border-amber-400 bg-amber-50 dark:bg-amber-900/30 rounded-r-md pl-3 py-1'"
        >
          <ForumCommentRow
            :comment="comment"
            :has-replies="getReplies(comment.id).length > 0"
            :user-id="userId"
            :is-mod="isMod"
            :lang="lang"
            :read-only="readOnly"
            @like="handleLike"
            @reply="handleReply"
            @refresh="loadComments"
          />
          <!-- Réponses -->
          <div v-if="getReplies(comment.id).length > 0" class="ml-7 mt-2 space-y-3 border-l-2 border-muted pl-3">
            <div
              v-for="reply in getReplies(comment.id)"
              :id="`comment-${reply.id}`"
              :key="reply.id"
              :class="reply.id === highlightCommentId
                ? 'border-l-4 border-green-500 bg-green-50 dark:bg-green-900/30 rounded-r-md -ml-3 pl-3 py-1'
                : reply.isStaff
                ? 'border-l-4 border-teal-400 bg-zinc-50 dark:bg-zinc-800/40 rounded-r-md -ml-3 pl-3 py-1'
                : ''"
            >
              <ForumCommentRow
                :comment="reply"
                :parent-comment="comment"
                :user-id="userId"
                :is-mod="isMod"
                :lang="lang"
                :read-only="readOnly"
                @like="handleLike"
                @reply="handleReply"
                @refresh="loadComments"
              />
            </div>
          </div>
        </div>
      </template>

      <hr v-if="pinned.length > 0 && regular.length > 0" class="my-1 border-border/30" />

      <!-- Commentaires normaux -->
      <template v-for="comment in regular" :key="comment.id">
        <div
          :id="`comment-${comment.id}`"
          :class="comment.id === highlightCommentId
            ? 'border-l-4 border-green-500 bg-green-50 dark:bg-green-900/30 rounded-r-md pl-3 py-1'
            : comment.isStaff
            ? 'border-l-4 border-teal-400 bg-zinc-50 dark:bg-zinc-800/40 rounded-r-md pl-3 py-1'
            : 'border-b border-border/30 last:border-0'"
        >
          <ForumCommentRow
            :comment="comment"
            :has-replies="getReplies(comment.id).length > 0"
            :user-id="userId"
            :is-mod="isMod"
            :lang="lang"
            :read-only="readOnly"
            @like="handleLike"
            @reply="handleReply"
            @refresh="loadComments"
          />
          <!-- Réponses -->
          <div v-if="getReplies(comment.id).length > 0" class="ml-7 mt-2 space-y-3 border-l-2 border-muted pl-3">
            <div
              v-for="reply in getReplies(comment.id)"
              :id="`comment-${reply.id}`"
              :key="reply.id"
              :class="reply.id === highlightCommentId
                ? 'border-l-4 border-green-500 bg-green-50 dark:bg-green-900/30 rounded-r-md -ml-3 pl-3 py-1'
                : reply.isStaff
                ? 'border-l-4 border-teal-400 bg-zinc-50 dark:bg-zinc-800/40 rounded-r-md -ml-3 pl-3 py-1'
                : ''"
            >
              <ForumCommentRow
                :comment="reply"
                :parent-comment="comment"
                :user-id="userId"
                :is-mod="isMod"
                :lang="lang"
                :read-only="readOnly"
                @like="handleLike"
                @reply="handleReply"
                @refresh="loadComments"
              />
            </div>
          </div>
        </div>
      </template>

      <!-- Formulaire nouveau commentaire -->
      <div v-if="!isArchived && !readOnly" class="space-y-2 pt-2">
        <p v-if="replyTo" class="text-xs text-muted-foreground">
          ↩️ {{ t('forum.replyTo') }}
          <strong>{{ replyTo.displayName }}</strong>
          <button class="ml-2 underline" @click="replyTo = null">{{ t('forum.cancel') }}</button>
        </p>
        <UTextarea
          v-model="commentText"
          :placeholder="t('forum.writeComment')"
          :rows="3"
        />
        <p v-if="error" class="text-sm text-red-500">{{ error }}</p>
        <UButton size="xs" :disabled="submitting || !commentText.trim()" @click="handleSubmitComment">
          {{ submitting ? '…' : t('forum.send') }}
        </UButton>
      </div>
    </template>
  </UCard>
</template>

// components/forum/SubjectCard.tsx
"use client";

import React, { useState, useRef, useEffect } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown } from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { t } from "@/lib/i18n";

const TYPE_PICTO: Record<string, string> = {
  question: "❓",
  share: "💬",
  request: "🙋",
  bug: "🐛",
  announcement: "📢",
};

export type SubjectData = {
  id: number;
  userId: number;
  displayName: string;
  type: string;
  title: string;
  content: string;
  status: string;
  isPinned: boolean;
  isStaff: boolean;
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string | null;
  _count: { comments: number };
};

export type CommentData = {
  id: number;
  forumSubjectId: number;
  forumCommentId: number | null;
  userId: number;
  displayName: string;
  addressedTo: string | null;
  destUserId: number | null;
  content: string;
  status: string;
  isPinned: boolean;
  isStaff: boolean;
  likes: number[];
  createdAt: string;
  updatedAt: string | null;
};

type Props = {
  subject: SubjectData;
  userId: number;
  userRole: string;
  displayName: string;
  isMod: boolean;
  lang: string;
  initialExpanded?: boolean;
  highlightCommentId?: number;
  onRefreshList?: () => void;
  readOnly?: boolean;
};

const URL_REGEX = /https?:\/\/[^\s]+/g;

function renderWithLinks(text: string) {
  const parts = text.split(URL_REGEX);
  const urls = text.match(URL_REGEX) ?? [];
  return parts.flatMap((part, i) => {
    const nodes: React.ReactNode[] = [part];
    if (urls[i]) {
      nodes.push(
        <a
          key={i}
          href={urls[i]}
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 underline hover:text-blue-700 break-all"
          onClick={(e) => e.stopPropagation()}
        >
          {urls[i]}
        </a>
      );
    }
    return nodes;
  });
}

const MONTHS: Record<string, string[]> = {
  fr: ["jan.", "fév.", "mar.", "avr.", "mai", "juin", "juil.", "août", "sep.", "oct.", "nov.", "déc."],
  es: ["ene.", "feb.", "mar.", "abr.", "may.", "jun.", "jul.", "ago.", "sep.", "oct.", "nov.", "dic."],
  en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
};

function formatDate(iso: string, lang: string) {
  const d = new Date(iso);
  const months = MONTHS[lang] ?? MONTHS.en;
  return `${d.getUTCDate()} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
}

export default function SubjectCard({ subject, userId, userRole, displayName, isMod, lang, initialExpanded = false, highlightCommentId, onRefreshList, readOnly = false }: Props) {
  const router = useRouter();
  const [expanded, setExpanded] = useState(initialExpanded);
  const highlightRef = useRef<HTMLDivElement>(null);
  const [comments, setComments] = useState<CommentData[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [replyTo, setReplyTo] = useState<CommentData | null>(null);

  const isSubjectOwner = subject.userId === userId;
  const [withinEditWindowSubject, setWithinEditWindowSubject] = useState(false);
  useEffect(() => {
    setWithinEditWindowSubject(Date.now() - new Date(subject.createdAt).getTime() < 3_600_000);
  }, [subject.createdAt]);
  const canEditSubject = !readOnly && isSubjectOwner && withinEditWindowSubject;
  const canDeleteSubject = !readOnly && (isSubjectOwner || isMod) && subject.status === "open";
  const isHiddenSubject = subject.status === "hidden";

  const [subjectContentExpanded, setSubjectContentExpanded] = useState(false);
  const isSubjectLong = subject.content.length > 200 || subject.content.split("\n").length > 3;
  const [isEditingSubject, setIsEditingSubject] = useState(false);
  const [editTitle, setEditTitle] = useState(subject.title);
  const [editContent, setEditContent] = useState(subject.content);
  const [savingSubject, setSavingSubject] = useState(false);
  const [confirmDeleteSubject, setConfirmDeleteSubject] = useState(false);
  const [commentText, setCommentText] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const picto = TYPE_PICTO[subject.type] ?? "📝";
  const isArchived = subject.status === "archived";
  const [canReactivate, setCanReactivate] = useState(false);
  useEffect(() => {
    if (isArchived && subject.updatedAt) {
      const oneMonthAgo = new Date();
      oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
      setCanReactivate(new Date(subject.updatedAt) > oneMonthAgo);
    } else {
      setCanReactivate(false);
    }
  }, [isArchived, subject.updatedAt]);

  async function loadComments() {
    setLoading(true);
    const res = await fetch(`/api/forum/subjects/${subject.id}/comments`);
    const data = await res.json();
    setComments(Array.isArray(data) ? data : []);
    setLoading(false);
  }

  useEffect(() => {
    if (initialExpanded) loadComments();
  }, []);

  useEffect(() => {
    if (highlightRef.current) {
      highlightRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [comments]);

  async function handleExpand() {
    const next = !expanded;
    setExpanded(next);
    if (next && comments === null) await loadComments();
  }

  async function handleSaveSubject() {
    if (!editTitle.trim() || !editContent.trim()) return;
    setSavingSubject(true);
    await fetch(`/api/forum/subjects/${subject.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "update", title: editTitle.trim(), content: editContent.trim() }),
    });
    setSavingSubject(false);
    setIsEditingSubject(false);
    router.refresh();
  }

  async function handleDeleteSubject() {
    await fetch(`/api/forum/subjects/${subject.id}`, { method: "DELETE" });
    router.refresh();
    onRefreshList?.();
  }

  async function handleUnarchiveSubject() {
    await fetch(`/api/forum/subjects/${subject.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "open" }),
    });
    onRefreshList?.();
  }

  async function handleToggleHideSubject() {
    await fetch(`/api/forum/subjects/${subject.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: isHiddenSubject ? "unhide" : "hide" }),
    });
    router.refresh();
    onRefreshList?.();
  }

  function handleReply(comment: CommentData) {
    setReplyTo(comment);
    setTimeout(() => textareaRef.current?.focus(), 0);
  }

  async function handleLike(commentId: number) {
    await fetch(`/api/forum/comments/${commentId}/like`, { method: "POST" });
    await loadComments();
  }

  async function handleSubmitComment() {
    if (!commentText.trim()) return;
    setSubmitting(true);
    setError("");
    const res = await fetch(`/api/forum/subjects/${subject.id}/comments`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content: commentText.trim(), forumCommentId: replyTo?.id ?? null }),
    });
    const data = await res.json();
    if (!res.ok) {
      setError(t(data.error, lang));
    } else {
      setCommentText("");
      setReplyTo(null);
      await loadComments();
    }
    setSubmitting(false);
  }

  const level0 = (comments ?? []).filter((c) => c.forumCommentId === null);
  const getReplies = (id: number) => (comments ?? []).filter((c) => c.forumCommentId === id);

  return (
    <Card className={
      subject.status === "hidden"
        ? "border-red-200 opacity-75"
        : subject.isStaff
        ? "border-l-4 border-l-teal-400 bg-zinc-50 dark:bg-zinc-800/40"
        : ""
    }>
      <CardHeader
        className="cursor-pointer select-none"
        onClick={handleExpand}
      >
        <div className="flex items-start gap-3">
          <span className="text-xl mt-0.5">{picto}</span>
          <div className="flex-1 min-w-0">
            <p className="font-semibold leading-tight">{subject.title}</p>
            <div className="flex flex-wrap items-center gap-2 mt-1">
              {subject.isPinned && <Badge variant="secondary">📌 {t("forum.pinned", lang)}</Badge>}
              {subject.status === "hidden" && isMod && <Badge variant="destructive">🚫 {t("forum.hidden", lang)}</Badge>}
              <span className="text-xs text-muted-foreground">
                <span className="font-medium text-foreground">{subject.displayName}</span>
                {" · "}
                {formatDate(subject.createdAt, lang)}
                {subject.updatedAt && (
                  <> · <span className="italic">{t("forum.modifiedOn", lang)} {formatDate(subject.updatedAt, lang)}</span></>
                )}
                {subject.expiresAt && (
                  <> · <span className={new Date(subject.expiresAt) < new Date() ? "text-destructive" : ""}>{t("forum.expiresOn", lang)} {formatDate(subject.expiresAt, lang)}</span></>
                )}
                {" · "}
                {subject._count.comments} {t(subject._count.comments === 1 ? "forum.comment" : "forum.comments", lang)}
              </span>
              <div className="flex gap-2 items-center" onClick={(e) => e.stopPropagation()}>
                {canEditSubject && !isEditingSubject && (
                  <button onClick={() => { setIsEditingSubject(true); setExpanded(true); }} className="text-xs text-muted-foreground hover:text-foreground transition-colors">✏️</button>
                )}
                {canDeleteSubject && (
                  confirmDeleteSubject ? (
                    <>
                      <button onClick={() => setConfirmDeleteSubject(false)} className="text-red-500 hover:text-red-600 transition-colors text-xs">✖</button>
                      <button onClick={handleDeleteSubject} className="text-green-500 hover:text-green-600 transition-colors text-xs">✔</button>
                    </>
                  ) : (
                    <button onClick={() => setConfirmDeleteSubject(true)} className="text-xs text-muted-foreground hover:text-destructive transition-colors">🗑️</button>
                  )
                )}
                {(isMod || isSubjectOwner) && canReactivate && (
                  <button
                    onClick={handleUnarchiveSubject}
                    className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                    title={t("forum.unarchive", lang)}
                  >
                    📂
                  </button>
                )}
                {isMod && subject.status !== "archived" && (
                  <button onClick={handleToggleHideSubject} className="text-xs text-muted-foreground hover:text-foreground transition-colors">
                    {isHiddenSubject ? "✅" : "🚫"}
                  </button>
                )}
              </div>
            </div>
          </div>
          <ChevronDown
            className={`w-4 h-4 mt-1 shrink-0 text-muted-foreground transition-transform ${expanded ? "rotate-180" : ""}`}
          />
        </div>
      </CardHeader>

      {expanded && (
        <CardContent className="space-y-1 pt-0 pb-3">
          {isEditingSubject ? (
            <div className="space-y-2 pb-2">
              <Input
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
                className="text-sm font-semibold"
                maxLength={255}
              />
              <Textarea
                value={editContent}
                onChange={(e) => setEditContent(e.target.value)}
                rows={5}
                className="text-sm"
              />
              <div className="flex gap-2">
                <Button size="sm" onClick={handleSaveSubject} disabled={savingSubject || !editTitle.trim() || !editContent.trim()}>
                  {savingSubject ? "…" : t("forum.save", lang)}
                </Button>
                <Button size="sm" variant="ghost" onClick={() => { setIsEditingSubject(false); setEditTitle(subject.title); setEditContent(subject.content); }}>
                  {t("forum.cancel", lang)}
                </Button>
              </div>
            </div>
          ) : (
            <>
              <p className={`text-sm whitespace-pre-wrap ${!subjectContentExpanded && isSubjectLong ? "overflow-hidden max-h-[3.75rem]" : ""}`}>
                {renderWithLinks(subject.content)}
              </p>
              {isSubjectLong && (
                <button
                  onClick={(e) => { e.stopPropagation(); setSubjectContentExpanded((v) => !v); }}
                  className="text-yellow-400 hover:text-yellow-500 transition-colors leading-none"
                >
                  {subjectContentExpanded ? "▲" : "▼"}
                </button>
              )}
            </>
          )}
          <Separator />

          {loading && <p className="text-sm text-muted-foreground">{t("common.loading", lang)}</p>}

          {!loading && comments !== null && comments.length === 0 && (
            <p className="text-sm text-muted-foreground">{t("forum.noComments", lang)}</p>
          )}

          {(() => {
            const pinned = level0.filter((c) => c.isPinned);
            const regular = level0.filter((c) => !c.isPinned);

            const renderComment = (comment: CommentData, isPinned = false) => {
              const isHighlighted = comment.id === highlightCommentId;
              return (
              <div
                key={comment.id}
                ref={isHighlighted ? highlightRef : undefined}
                className={
                  isHighlighted
                    ? "border-l-4 border-green-500 bg-green-50 dark:bg-green-900/30 rounded-r-md pl-3 py-1"
                    : isPinned
                    ? "border-l-4 border-amber-400 bg-amber-50 dark:bg-amber-900/30 rounded-r-md pl-3 py-1"
                    : comment.isStaff
                    ? "border-l-4 border-teal-400 bg-zinc-50 dark:bg-zinc-800/40 rounded-r-md pl-3 py-1"
                    : "border-b border-border/30 last:border-0"
                }
              >
                <CommentRow
                  comment={comment}
                  hasReplies={getReplies(comment.id).length > 0}
                  userId={userId}
                  isMod={isMod}
                  lang={lang}
                  readOnly={readOnly}
                  onLike={handleLike}
                  onReply={handleReply}
                  onRefresh={loadComments}
                />
                {getReplies(comment.id).length > 0 && (
                  <div className="ml-7 mt-2 space-y-3 border-l-2 border-muted pl-3">
                    {getReplies(comment.id).map((reply) => {
                      const isReplyHighlighted = reply.id === highlightCommentId;
                      return (
                        <div
                          key={reply.id}
                          ref={isReplyHighlighted ? highlightRef : undefined}
                          className={
                            isReplyHighlighted
                              ? "border-l-4 border-green-500 bg-green-50 dark:bg-green-900/30 rounded-r-md -ml-3 pl-3 py-1"
                              : reply.isStaff
                              ? "border-l-4 border-teal-400 bg-zinc-50 dark:bg-zinc-800/40 rounded-r-md -ml-3 pl-3 py-1"
                              : ""
                          }
                        >
                          <CommentRow
                            comment={reply}
                            parentComment={comment}
                            userId={userId}
                            isMod={isMod}
                            lang={lang}
                            readOnly={readOnly}
                            onLike={handleLike}
                            onReply={handleReply}
                            onRefresh={loadComments}
                          />
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
              );
            };

            return (
              <>
                {pinned.map((c) => renderComment(c, true))}
                {pinned.length > 0 && regular.length > 0 && (
                  <Separator className="my-1" />
                )}
                {regular.map((c) => renderComment(c, false))}
              </>
            );
          })()}

          {!isArchived && !readOnly && (
            <div className="space-y-2 pt-2">
              {replyTo && (
                <p className="text-xs text-muted-foreground">
                  ↩️ {t("forum.replyTo", lang)}{" "}
                  <strong>{replyTo.displayName}</strong>
                  <button
                    onClick={() => setReplyTo(null)}
                    className="ml-2 underline"
                  >
                    {t("forum.cancel", lang)}
                  </button>
                </p>
              )}
              <Textarea
                ref={textareaRef}
                placeholder={t("forum.writeComment", lang)}
                value={commentText}
                onChange={(e) => setCommentText(e.target.value)}
                rows={3}
              />
              {error && <p className="text-sm text-red-500">{error}</p>}
              <Button
                size="sm"
                onClick={handleSubmitComment}
                disabled={submitting || !commentText.trim()}
              >
                {submitting ? "…" : t("forum.send", lang)}
              </Button>
            </div>
          )}
        </CardContent>
      )}
    </Card>
  );
}

type CommentRowProps = {
  comment: CommentData;
  parentComment?: CommentData | null;
  hasReplies?: boolean;
  userId: number;
  isMod: boolean;
  lang: string;
  readOnly?: boolean;
  onLike: (id: number) => void;
  onReply: (c: CommentData) => void;
  onRefresh: () => void;
};

function CommentRow({ comment, parentComment, hasReplies = false, userId, isMod, lang, readOnly = false, onLike, onReply, onRefresh }: CommentRowProps) {
  const likes = Array.isArray(comment.likes) ? (comment.likes as number[]) : [];
  const liked = likes.includes(userId);
  const isLevel1 = comment.forumCommentId !== null;
  const [expanded, setExpanded] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editText, setEditText] = useState(comment.content);
  const [saving, setSaving] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const isLong = comment.content.length > 200 || comment.content.split("\n").length > 3;

  const isOwner = comment.userId === userId;
  const [withinEditWindow, setWithinEditWindow] = useState(false);
  useEffect(() => {
    setWithinEditWindow(Date.now() - new Date(comment.createdAt).getTime() < 3_600_000);
  }, [comment.createdAt]);
  const canEdit = !readOnly && isOwner && withinEditWindow;
  const canDelete = !readOnly && isOwner && !hasReplies;
  const isHidden = comment.status === "hidden";

  if (isHidden && !isMod) return null;

  async function handleSaveEdit() {
    if (!editText.trim()) return;
    setSaving(true);
    await fetch(`/api/forum/comments/${comment.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "update", content: editText.trim() }),
    });
    setSaving(false);
    setIsEditing(false);
    onRefresh();
  }

  async function handleDelete() {
    await fetch(`/api/forum/comments/${comment.id}`, { method: "DELETE" });
    onRefresh();
  }

  async function handleToggleHide() {
    await fetch(`/api/forum/comments/${comment.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: isHidden ? "unhide" : "hide" }),
    });
    onRefresh();
  }

  return (
    <div className={`flex gap-2 ${isHidden ? "text-red-400" : ""}`}>
      <span className="text-base mt-0.5">{isLevel1 ? "↩️" : "🗨️"}</span>
      <div className="flex-1 min-w-0">
        <div className="flex items-baseline gap-1 flex-wrap text-xs text-muted-foreground">
          <span className="font-medium">{comment.displayName}</span>
          <span>· {formatDate(comment.createdAt, lang)}</span>
          {isLevel1 && comment.addressedTo && parentComment && (
            <span className="text-xs text-muted-foreground">
              (→ {comment.addressedTo} · {formatDate(parentComment.createdAt, lang)})
            </span>
          )}
          {isHidden && isMod && <span className="text-xs text-destructive">🚫</span>}
          <div className="flex gap-3 items-center">
            {!readOnly && (
              <button onClick={() => onLike(comment.id)} className="text-xs text-muted-foreground hover:text-foreground transition-colors">
                {liked ? "❤️" : "🤍"}{likes.length > 0 ? ` ${likes.length}` : ""}
              </button>
            )}
            {!readOnly && !isEditing && (
              <button onClick={() => onReply(comment)} className="text-xs text-muted-foreground hover:text-foreground transition-colors">
                ↩️
              </button>
            )}
            {canEdit && !isEditing && (
              <button onClick={() => setIsEditing(true)} className="text-xs text-muted-foreground hover:text-foreground transition-colors">
                ✏️
              </button>
            )}
            {canDelete && (
              confirmDelete ? (
                <>
                  <button onClick={() => setConfirmDelete(false)} className="text-red-500 hover:text-red-600 transition-colors text-xs">✖</button>
                  <button onClick={handleDelete} className="text-green-500 hover:text-green-600 transition-colors text-xs">✔</button>
                </>
              ) : (
                <button onClick={() => setConfirmDelete(true)} className="text-xs text-muted-foreground hover:text-destructive transition-colors">
                  🗑️
                </button>
              )
            )}
            {isMod && !readOnly && !isLevel1 && (
              <button
                onClick={async () => {
                  await fetch(`/api/forum/comments/${comment.id}`, {
                    method: "PATCH",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ action: comment.isPinned ? "unpin" : "pin" }),
                  });
                  onRefresh();
                }}
                className="text-xs text-muted-foreground hover:text-foreground transition-colors"
              >
                {comment.isPinned ? "📌" : "📍"}
              </button>
            )}
            {isMod && (
              <button onClick={handleToggleHide} className="text-xs text-muted-foreground hover:text-foreground transition-colors">
                {isHidden ? "✅" : "🚫"}
              </button>
            )}
          </div>
        </div>

        {isEditing ? (
          <div className="mt-1 space-y-1">
            <Textarea
              value={editText}
              onChange={(e) => setEditText(e.target.value)}
              rows={4}
              className="text-sm"
            />
            <div className="flex gap-2">
              <Button size="sm" onClick={handleSaveEdit} disabled={saving || !editText.trim()}>
                {saving ? "…" : t("forum.save", lang)}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => { setIsEditing(false); setEditText(comment.content); }}>
                {t("forum.cancel", lang)}
              </Button>
            </div>
          </div>
        ) : (
          <>
            <p className={`text-sm mt-0.5 whitespace-pre-wrap ${!expanded && isLong ? "overflow-hidden max-h-[3.75rem]" : ""}`}>
              {renderWithLinks(comment.content)}
            </p>
            {isLong && (
              <button onClick={() => setExpanded((v) => !v)} className="text-yellow-400 hover:text-yellow-500 transition-colors leading-none">
                {expanded ? "▲" : "▼"}
              </button>
            )}
          </>
        )}
      </div>
    </div>
  );
}
