// app/subscriber/download/page.tsx
import { getLang } from "@/lib/getLang";
import { t } from "@/lib/i18n";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";

export default async function DownloadPage() {
  const lang = await getLang();
  const resourcesUrl = process.env.RESOURCES_URL ?? "#";

  return (
    <main className="container mx-auto py-10">
      <h1 className="text-2xl font-bold mb-8">{t("download.title", lang)}</h1>
      <Card className="max-w-md">
        <CardHeader>
          <CardTitle>{t("download.cardTitle", lang)}</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground mb-4">{t("download.description", lang)}</p>
          <a href={resourcesUrl} target="_blank" rel="noopener noreferrer" className={buttonVariants()}>
            {t("download.openSheets", lang)}
          </a>
        </CardContent>
      </Card>
    </main>
  );
}

// app/pages/subscriber/download.vue
<script setup lang="ts">
const { t } = useI18n()

const { data } = await useFetch('/api/subscriber/resources-url')
const resourcesUrl = computed(() => data.value?.url ?? '#')
</script>

<template>
  <main class="container mx-auto py-10">
    <h1 class="text-2xl font-bold mb-8">{{ t('download.title') }}</h1>
    <UCard class="max-w-md">
      <template #header>
        <h2 class="font-semibold">{{ t('download.cardTitle') }}</h2>
      </template>
      <p class="text-muted-foreground mb-4">{{ t('download.description') }}</p>
      <a :href="resourcesUrl" target="_blank" rel="noopener noreferrer">
        <UButton>{{ t('download.openSheets') }}</UButton>
      </a>
    </UCard>
  </main>
</template>
