// app/subscriber/myspace/page.tsx
import { getSession } from "@/lib/auth";
import { getByCodes } from "@/services/TrainingService";
import { getByUser } from "@/services/UserTrainingService";
import { t } from "@/lib/i18n";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import Link from "next/link";

export default async function MyspacePage() {
  const session = await getSession();
  const lang = session.language ?? "fr";

  const [trainings, purchases] = await Promise.all([
    getByCodes(session.trainings ?? []),
    getByUser(session.id),
  ]);

  const purchaseMap = new Map(purchases.map((p) => [p.trainingCode, p]));

  return (
    <main className="container mx-auto py-10 space-y-8">
      <h1 className="text-2xl font-bold">{t("myspace.title", lang)}</h1>

      <Card>
        <CardHeader>
          <CardTitle>{t("myspace.resources", lang)}</CardTitle>
        </CardHeader>
        <CardContent>
          <Link href="/subscriber/download" className={buttonVariants()}>
            {t("myspace.download", lang)}
          </Link>
        </CardContent>
      </Card>

      {session.communityAccess && (
        <Card>
          <CardHeader>
            <CardTitle>{t("community.title", lang)}</CardTitle>
          </CardHeader>
          <CardContent>
            <Link href="/community" className={buttonVariants()}>
              {t("community.access", lang)}
            </Link>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>{t("myspace.formations", lang)}</CardTitle>
        </CardHeader>
        <CardContent>
          {trainings.length === 0 ? (
            <div className="space-y-3">
              <p className="text-muted-foreground">{t("myspace.noPurchase", lang)}</p>
              <Link href="/catalog" className={buttonVariants({ variant: "outline" })}>
                {t("myspace.viewCatalog", lang)}
              </Link>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{t("myspace.colTitle", lang)}</TableHead>
                  <TableHead>{t("myspace.colPrice", lang)}</TableHead>
                  <TableHead></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {trainings.map((training) => {
                  const purchase = purchaseMap.get(training.code);
                  const price =
                    purchase?.amountCt != null
                      ? `${(purchase.amountCt / 100).toFixed(2)} ${(purchase.currency ?? "").toUpperCase()}`
                      : t("myspace.freeAccess", lang);
                  return (
                    <TableRow key={training.id}>
                      <TableCell className="font-medium">{training.title}</TableCell>
                      <TableCell>{price}</TableCell>
                      <TableCell className="text-right">
                        <Link
                          href={training.privatePageUrl ?? "/catalog"}
                          className={buttonVariants({ size: "sm" })}
                        >
                          {t("myspace.access", lang)}
                        </Link>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </main>
  );
}

// app/pages/subscriber/myspace.vue
<script setup lang="ts">
const { t } = useI18n()

const session = useState<any>('app-session')

const { data } = await useFetch('/api/subscriber/myspace')

const trainings = computed(() => data.value?.trainings ?? [])
const purchases = computed(() => data.value?.purchases ?? [])

const purchaseMap = computed(() => {
  const map = new Map<string, any>()
  for (const p of purchases.value) map.set(p.trainingCode, p)
  return map
})

function formatPrice(training: any): string {
  const purchase = purchaseMap.value.get(training.code)
  if (purchase?.amountCt != null) {
    return `${(purchase.amountCt / 100).toFixed(2)} ${(purchase.currency ?? '').toUpperCase()}`
  }
  return t('myspace.freeAccess')
}
</script>

<template>
  <main class="container mx-auto py-10 space-y-8">
    <h1 class="text-2xl font-bold">{{ t('myspace.title') }}</h1>

    <!-- Ressources -->
    <UCard>
      <template #header>
        <h2 class="font-semibold">{{ t('myspace.resources') }}</h2>
      </template>
      <NuxtLink to="/subscriber/download">
        <UButton>{{ t('myspace.download') }}</UButton>
      </NuxtLink>
    </UCard>

    <!-- Communauté -->
    <UCard v-if="session?.communityAccess">
      <template #header>
        <h2 class="font-semibold">{{ t('community.title') }}</h2>
      </template>
      <NuxtLink to="/community">
        <UButton>{{ t('community.access') }}</UButton>
      </NuxtLink>
    </UCard>

    <!-- Formations -->
    <UCard>
      <template #header>
        <h2 class="font-semibold">{{ t('myspace.formations') }}</h2>
      </template>

      <div v-if="trainings.length === 0" class="space-y-3">
        <p class="text-muted-foreground">{{ t('myspace.noPurchase') }}</p>
        <NuxtLink to="/catalog">
          <UButton variant="outline">{{ t('myspace.viewCatalog') }}</UButton>
        </NuxtLink>
      </div>

      <table v-else class="w-full text-sm">
        <thead>
          <tr class="border-b border-border">
            <th class="text-left py-2 px-3 font-medium text-muted-foreground">{{ t('myspace.colTitle') }}</th>
            <th class="text-left py-2 px-3 font-medium text-muted-foreground">{{ t('myspace.colPrice') }}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="training in trainings" :key="training.id" class="border-b border-border last:border-0">
            <td class="py-2 px-3 font-medium">{{ training.title }}</td>
            <td class="py-2 px-3">{{ formatPrice(training) }}</td>
            <td class="py-2 px-3 text-right">
              <NuxtLink :to="training.privatePageUrl ?? '/catalog'">
                <UButton size="sm">{{ t('myspace.access') }}</UButton>
              </NuxtLink>
            </td>
          </tr>
        </tbody>
      </table>
    </UCard>
  </main>
</template>
